# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools numpy scipy pytest matplotlib icecream scikit.rf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: install swig3.0 (g++, buildtools and fortran already installed)
      run: |
        sudo apt install -y swig3.0

    - name: Compile
      run: |
        git submodule init
        git submodule update --remote
        cd python-necpp
        git submodule init
        git submodule update --remote
        cd PyNEC
        ln -s ../necpp_src .
        pushd ../necpp_src
        make -f Makefile.git
        ./configure --without-lapack
        popd
        swig3.0 -Wall -v -c++ -python PyNEC.i
        python setup.py build
        python setup.py install

    - name: Test with pytest
      run: |
        pip install -e .
        pytest -vv --durations=0 -- tests/
